# Generated by Django 6.0.2 on 2026-04-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('established_date', models.DateField(verbose_name='Дата основания')),
                ('founders', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основатель(и)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='space_agencies/', verbose_name='Изображение компании')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штаб-квартира')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('CEO', models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор')),
                ('revenue_2025', models.DecimalField(blank=True, decimal_places=2, help_text='В миллионах долларов США', max_digits=15, null=True, verbose_name='Прибыль (2025, млн USD)')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Название планеты')),
                ('order', models.IntegerField(verbose_name='Порядок от солнца')),
                ('planet_type', models.CharField(choices=[('TER', 'Земная группа'), ('GAS', 'Газовый гигант'), ('ICE', 'Ледяной гигант'), ('DWA', 'Карликовая планета')], default='TER', max_length=3, verbose_name='Тип планеты')),
                ('radius', models.FloatField(verbose_name='Радиус (км)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст планеты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='planets/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название агентства')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('established_date', models.DateField(verbose_name='Дата основания')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание агентства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='space_agencies/', verbose_name='Изображение агентства')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Название спутника')),
                ('satellite_type', models.CharField(choices=[('REG', 'Регулярный (сферический)'), ('IRR', 'Нерегулярный (астероидный)'), ('PRO', 'Временный (захваченный)')], default='REG', max_length=3, verbose_name='Тип спутника')),
                ('radius', models.FloatField(verbose_name='Радиус (км)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст спутника')),
                ('image', models.ImageField(blank=True, null=True, upload_to='satellites/', verbose_name='Изображение')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satellites', to='planets.planet', verbose_name='Планета-хозяин')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название миссии')),
                ('mission_type', models.CharField(choices=[('MRV', 'Марсоход'), ('TEL', 'Телескоп'), ('STA', 'Космическая станция'), ('ORB', 'Орбитальный аппарат'), ('OTH', 'Другая')], default='OTH', max_length=3, verbose_name='Тип миссии')),
                ('launch_date', models.DateField(verbose_name='Дата запуска')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('planned', 'Планируется')], default='planned', max_length=10, verbose_name='Статус')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (дней)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание миссии')),
                ('success', models.BooleanField(default=False, verbose_name='Успешность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/', verbose_name='Изображение миссии')),
                ('target_planets', models.ManyToManyField(blank=True, to='planets.planet', verbose_name='Цели (планеты)')),
                ('target_satellites', models.ManyToManyField(blank=True, to='planets.satellite', verbose_name='Цели (спутники)')),
                ('space_agency', models.ManyToManyField(related_name='missions', to='planets.spaceagency', verbose_name='Космические агентства')),
            ],
        ),
    ]
