# Generated by Django 6.0.2 on 2026-03-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.TextField(max_length=20, verbose_name='Название планеты')),
                ('planet_orger', models.IntegerField(verbose_name='Порядок от солнца')),
                ('planet_type', models.CharField(choices=[('TER', 'Земная группа'), ('GAS', 'Газовый гигант'), ('ICE', 'Ледяной гигант'), ('DWA', 'Карликовая планета')], default='TER', max_length=3, verbose_name='Тип планеты')),
                ('planet_radius', models.IntegerField(verbose_name='Радиус (км)')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.TextField(max_length=20, verbose_name='Название спутника')),
                ('satellite_type', models.CharField(choices=[('REG', 'Регулярный (сферический)'), ('IRR', 'Нерегулярный (астероидный)'), ('PRO', 'Временный (захваченный)'), ('ART', 'Искусственный (станции\\зонды)')], default='REG', max_length=3, verbose_name='Тип спутника')),
                ('satellite_radius', models.IntegerField(verbose_name='Радиус (км)')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satellites', to='planets.planets', verbose_name='Планета-хозяин')),
            ],
        ),
    ]
