# Generated by Django 6.0.2 on 2026-03-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planets',
            new_name='Planet',
        ),
    ]
