# Generated by Django 6.0.2 on 2026-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_rename_planets_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='planet_radius',
            field=models.FloatField(verbose_name='Радиус (км)'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='satellite_radius',
            field=models.FloatField(verbose_name='Радиус (км)'),
        ),
    ]
