# Generated by Django 6.0.2 on 2026-03-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alter_planet_planet_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL-метка'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL-метка'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_orger',
            field=models.IntegerField(verbose_name='Порядок от Солнца'),
        ),
    ]
