# Generated by Django 6.0.2 on 2026-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_planet_slug_satellite_slug_alter_planet_planet_orger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='slug',
        ),
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planets/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_text',
            field=models.TextField(default='', verbose_name='Текст планеты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='satellites/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='satellite_text',
            field=models.TextField(default=' ', verbose_name='Текст спутника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_orger',
            field=models.IntegerField(verbose_name='Порядок от солнца'),
        ),
    ]
