# Generated by Django 6.0.2 on 2026-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0005_remove_planet_slug_remove_satellite_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='satellite_text',
            field=models.TextField(null=True, verbose_name='Текст спутника'),
        ),
    ]
