# Generated by Django 6.0.2 on 2026-03-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0006_alter_satellite_satellite_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='planet_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст планеты'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='satellite_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст спутника'),
        ),
    ]
