# Generated by Django 6.0.2 on 2026-03-29 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0007_alter_planet_planet_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название агентства')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('established_date', models.DateField(verbose_name='Дата основания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание агентства')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=50, verbose_name='Название миссии')),
                ('mission_type', models.CharField(choices=[('MRV', 'Марсоход'), ('TEL', 'Телескоп'), ('STA', 'Космическая станция'), ('RES', 'Поставка'), ('OTH', 'Другая')], default='OTH', max_length=3, verbose_name='Тип миссии')),
                ('launch_date', models.DateField(verbose_name='Дата запуска')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание миссии')),
                ('success', models.BooleanField(default=False, verbose_name='Успешность')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='missions/', verbose_name='Изображение миссии')),
                ('target_planets', models.ManyToManyField(blank=True, related_name='missions_targeted', to='planets.planet')),
                ('target_satellites', models.ManyToManyField(blank=True, related_name='missions_targeted', to='planets.satellite')),
                ('space_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='planets.spaceagency', verbose_name='Космическое агентство')),
            ],
        ),
    ]
