# Generated by Django 6.0.2 on 2026-03-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0008_spaceagency_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='satellite_type',
            field=models.CharField(choices=[('REG', 'Регулярный (сферический)'), ('IRR', 'Нерегулярный (астероидный)'), ('PRO', 'Временный (захваченный)')], default='REG', max_length=3, verbose_name='Тип спутника'),
        ),
    ]
