# Generated by Django 6.0.2 on 2026-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0009_alter_satellite_satellite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceagency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='space_agencies/', verbose_name='Изображение агентства'),
        ),
    ]
