# Generated by Django 6.0.2 on 2026-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0010_spaceagency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='target_planets',
            field=models.ManyToManyField(blank=True, to='planets.planet', verbose_name='Цели (планеты)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='target_satellites',
            field=models.ManyToManyField(blank=True, to='planets.satellite', verbose_name='Цели (спунтики)'),
        ),
    ]
