# Generated by Django 6.0.2 on 2026-03-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0011_alter_mission_target_planets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='space_agency',
        ),
        migrations.AddField(
            model_name='mission',
            name='space_agency',
            field=models.ManyToManyField(related_name='missions', to='planets.spaceagency', verbose_name='Космические агентства'),
        ),
    ]
