# Generated by Django 6.0.2 on 2026-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0012_remove_mission_space_agency_mission_space_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('planned', 'Планируется')], default='planned', max_length=10, verbose_name='Статус'),
        ),
    ]
