# Generated by Django 6.0.2 on 2026-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0013_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (дней)'),
        ),
    ]
