# Generated by Django 6.0.2 on 2026-03-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0014_alter_mission_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('MRV', 'Марсоход'), ('TEL', 'Телескоп'), ('STA', 'Космическая станция'), ('ORB', 'Орбитальный аппарат'), ('OTH', 'Другая')], default='OTH', max_length=3, verbose_name='Тип миссии'),
        ),
    ]
