# Generated by Django 6.0.2 on 2026-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0015_alter_mission_mission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('planned', 'Планируется')], default='planned', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='target_satellites',
            field=models.ManyToManyField(blank=True, to='planets.satellite', verbose_name='Цели (спутники)'),
        ),
    ]
