# Generated by Django 6.0.2 on 2026-03-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0016_rename_mission_image_mission_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaceagency',
            old_name='description',
            new_name='text',
        ),
    ]
