# Generated by Django 6.0.2 on 2026-03-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0017_rename_description_spaceagency_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='planet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='planet_orger',
            new_name='orger',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='planet_radius',
            new_name='radius',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='planet_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='satellite',
            old_name='satellite_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='satellite',
            old_name='satellite_radius',
            new_name='radius',
        ),
        migrations.RenameField(
            model_name='satellite',
            old_name='satellite_text',
            new_name='text',
        ),
    ]
