# Generated by Django 6.0.2 on 2026-03-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0018_rename_mission_name_mission_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='orger',
            new_name='order',
        ),
    ]
